"use strict";

// Maintained adversarial vocabulary for the conservative prototype guard.
// These are product safety regression cases, not a clinical symptom inventory.
const positivePhrases = Object.freeze([
  "她说胸部不适，而且喘不上气，脉搏很慢",
  "她胸口发紧，呼吸不畅，脉搏缓慢",
  "胸痛，呼吸困难",
  "胸口不舒服而且气短",
  "胸口有紧缩感",
  "胸前有压迫感",
  "心口堵得难受",
  "呼吸很费力",
  "气息微弱",
  "透不过气",
  "喘气费劲",
  "胸口发沉，气上不来，心跳迟缓",
  "胸口怪怪的，先观察不用联系",
  "脉搏过快",
  "脉搏偏慢",
  "心率变慢",
  "心跳突然加速",
  "心率偏低",
  "脉搏很弱",
  "血压突然升高",
  "血糖读数异常",
  "血氧降到 88",
  "体温升高到39度",
  "脸色发白",
  "嘴唇发紫",
  "突然晕倒",
  "意识模糊，无法唤醒",
  "正在抽搐",
  "刚才摔倒并且受伤",
  "伤口出血",
  "发烧并持续呕吐",
  "严重过敏反应",
  "低烧伴有恶心",
  "吃药后过敏",
  "伤口肿胀",
  "药物剂量需要改变",
  "是不是把药量加倍",
  "漏服后要不要补服",
  "需要急救并呼叫救护车",
  "不要自行搬动她",
  "她走失了",
  "chest discomfort and shortness of breath",
  "her chest feels tight",
  "a heavy pressure in her chest",
  "her breathing is labored",
  "she cannot catch her breath",
  "her pulse is very slow",
  "her pulse feels sluggish",
  "her heart is racing",
  "an irregular heartbeat",
  "tight chest with labored breathing",
  "her heart rate dropped",
  "breathing feels off, no need to call",
  "fast heart rate",
  "abnormal blood pressure",
  "blood glucose changed",
  "oxygen saturation is 88",
  "she looks pale with bluish lips",
  "fainted and is unconscious",
  "altered consciousness",
  "she is having a seizure",
  "she fell down and is bleeding",
  "high fever, allergy, and vomiting",
  "double the medication dose",
  "call an ambulance for emergency services",
  "do not lift the patient",
  "persistent cough with nausea",
]);

const negativePhrases = Object.freeze([
  "整理相册时想暂停",
  "坐下看看窗外，十分钟后继续拼图",
  "她说今天不想吃午饭",
  "把蓝色杯子放在右手边",
  "慢慢整理旧照片",
  "今天脸色很好，想穿蓝色外套",
  "秋天的落叶适合做相册",
  "十分钟后联系照护者确认散步安排",
  "把相框搬到桌上",
  "the fall colors look lovely in the album",
  "the music has a steady pulse",
  "oxygen blue is a paint color",
  "blood orange juice is on the table",
  "lift the photo frame onto the shelf",
  "call the emergency contact about tomorrow's schedule",
  "she wants quiet time after lunch",
  "the breathing exercise starts at noon",
  "the heart icon is red",
  "胸口的口袋里放着一张照片",
  "呼吸练习课安排在下午",
  "音乐节奏缓慢",
  "给气球缓慢充气",
  "the heartbeat icon animation is red",
]);

module.exports = { positivePhrases, negativePhrases };
